# Eager execution

Tensorflow Eager Execution은 그래프 생성 없이 연산을 즉시 실행하는 명령형 프로그램이 환경  
각 연산들은 나중에 실행할 계산 그래프를 만드는 것이 아니라, 실제 값이 반환  
이를 통해 텐서플로우를 좀 더 쉽게 시작할 수 있고, 모델을 디버그할 수 있으며 불필요한 상용구도 줄어듬

In [1]:
import tensorflow as tf

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x = [[2.]]
m = tf.matmul(x, x)
print("result, {}".format(m))

result, Tensor("MatMul:0", shape=(1, 1), dtype=float32)


In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x = [[2.]]
m = tf.matmul(x, x)
print("result, {}".format(m))

result, [[4.]]


# Setup and Basic Usage

In [3]:
c = tf.constant(1)
c

<tf.Tensor: id=4, shape=(), dtype=int32, numpy=1>

# Numpy 호환성

Eager execution은 Numpy와 호환성이 매우 뛰어남  
Numpy 연산은 tf.Tensor를 인자로 받음  
텐서플로우 수학 연산은 파이썬 객체와 Numpy 배열을 tf.Tensor 객체로 변환  
tf.Tensor.numpy 함수는 객체의 값을 Numpy ndarray 형태로 반환

In [4]:
print(c.numpy())
print(type(c))
print(type(c.numpy()))

1
<class 'EagerTensor'>
<class 'numpy.int32'>


## Check the execution

In [6]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
# 브로드캐스팅을 지원합니다.
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [8]:
# 연산자 오버로딩을 지원합니다.
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [9]:
# NumPy 값을 써봅시다.
import numpy as np

c = np.multiply(a, b)
print(c)
print(a.numpy())

[[ 2  6]
 [12 20]]
[[1 2]
 [3 4]]


# Dynamic control flow

In [1]:
import tensorflow as tf

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(12)
a = 2 * a
print(a)

Tensor("mul:0", shape=(), dtype=int32)


In [3]:
a = tf.constant(12)
counter = 0
while not tf.equal(a, 1):
    if tf.equal(a % 2, 0):
        a = a / 2
    else:
        a = 3 * a + 1
    print(a)

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.